apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ingress-consul-register
  name: ingress-consul-register
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-consul-register
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ingress-consul-register
    spec:
      containers:
      - image: aswinkarthik93/ingress-consul-register:latest
        args:
          - /ingress-consul-register
          - start
          - --ingress-class
          - nginx-internal
          - --consul-controller-service
          - internal
          - --ingress-controller-service
          - router-nginx-ingress-controller
          - --consul-host
          - dns-consul
        imagePullPolicy: IfNotPresent
        name: ingress-consul-register
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
