apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: consul.internal.service.consul
    http:
      paths:
      - backend:
          serviceName: dns-consul-ui
          servicePort: 8500
